apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: utcop
  labels:
    app: redis-cluster
    env: dev
spec:
  ports:
  - name: http
    port: 6379
  selector:
    app: redis-cluster